from enum import Enum


class OBJECT_DATA(Enum):
    DEFAULT = "default"


def get_object_dicts(key):
    if key == OBJECT_DATA.DEFAULT:
        obj = STARTING_OBJECTS()
    else:
        raise Exception("Object class does not exist")

    return obj.return_items()


class OBJECT_CLASS:

    def __init__(self):
        self.damage_dict = {}
        self.object_list = []
        self.backgrounds = []

    def return_items(self):
        return self.object_list, self.damage_dict, self.backgrounds


class STARTING_OBJECTS(OBJECT_CLASS):
    def __init__(self):
        super().__init__()
        self.damage_dict = {
            "apple": [
                "bruised",
                "wrinkled",
                "rotten",
                "moldy",
                "dented",
                "discolored",
                "soft spots",
            ],
            "banana": [
                "bruised",
                "overripe",
                "blackened",
                "split peel",
                "mushy",
                "spotted",
            ],
            "carrot": ["softened", "cracked", "dehydrated", "spotted", "moldy", "bent"],
            "potato": [
                "sprouted",
                "rotting",
                "green spots",
                "wrinkled",
                "moldy",
                "soft spots",
            ],
            "egg": [
                "cracked",
                "leaking",
                "discolored shell",
                "dented",
                "rotten",
                "thin shell",
            ],
            "bread": ["stale", "moldy", "crumbling", "burnt", "hardened", "soggy"],
            "cheese": [
                "moldy",
                "dried out",
                "cracked",
                "discolored",
                "sweating",
                "crumbly",
            ],
            "butter": ["rancid", "melted", "discolored", "greasy residue", "hardened"],
            "milk carton": [
                "dented",
                "leaking",
                "stained",
                "faded label",
                "torn packaging",
            ],
            "chocolate bar": ["melted", "bloomed", "crumbled", "discolored"],
            "cookies": ["crumbled", "stale", "burnt", "moldy"],
            "apple slice": ["oxidized", "bruised", "dried out"],
            "orange": ["dried skin", "moldy", "bruised", "discolored"],
            "grape": ["wrinkled", "moldy", "shriveled"],
            "strawberry": ["moldy", "bruised", "shrinking"],
            "lettuce": ["wilting", "yellowing", "rotting"],
            "tomato": ["soft spots", "cracked skin", "moldy"],
            "onion": ["sprouted", "dried layers", "rotting"],
            "garlic": ["sprouted", "dried out", "moldy"],
            "hammer": ["rusty", "chipped", "bent", "dented", "scratched", "loose head"],
            "screwdriver": ["worn tip", "rusty", "scratched", "bent", "cracked handle"],
            "wrench": ["rusty", "scratched", "dented", "worn edges", "corroded"],
            "pliers": ["rusty", "loose grip", "scratched", "chipped", "stiff joint"],
            "saw": ["rusty blade", "dull teeth", "chipped handle", "bent blade"],
            "drill": [
                "worn chuck",
                "scratched casing",
                "broken switch",
                "dented battery",
            ],
            "tape measure": ["cracked casing", "faded markings", "stuck mechanism"],
            "paintbrush": ["frayed bristles", "stiffened bristles", "dried paint"],
            "shovel": ["rusty blade", "dented handle", "worn grip"],
            "rake": ["bent tines", "rusty", "loose handle"],
            "ball": ["deflated", "scuffed", "punctured", "faded", "cracked surface"],
            "doll": [
                "torn clothing",
                "missing eye",
                "stained",
                "frayed hair",
                "loose limbs",
            ],
            "teddy bear": [
                "ripped seam",
                "matted fur",
                "faded color",
                "stained",
                "missing stuffing",
            ],
            "yo-yo": ["scratched", "cracked", "tangled string", "chipped edge"],
            "kite": ["torn fabric", "bent frame", "frayed string", "missing tail"],
            "toy car": [
                "scratched paint",
                "missing wheel",
                "cracked body",
                "loose parts",
            ],
            "board game": ["torn box", "missing pieces", "faded board", "bent cards"],
            "lamp": ["flickering", "scratched base", "broken switch"],
            "chair": ["scratched wood", "stained cushion", "wobbly leg"],
            "table": ["scratched surface", "dented corner", "water stains"],
            "window": ["scratched glass", "cracked", "foggy"],
            "mirror": ["scratched", "chipped edge", "cloudy", "stained surface"],
            "carpet": ["stained", "frayed edges", "worn patches"],
            "toothbrush": ["frayed bristles", "stained", "bent handle", "worn grip"],
            "toothpaste tube": ["dented", "leaking", "crumpled", "worn cap"],
            "wallet": [
                "worn edges",
                "cracked leather",
                "faded color",
                "frayed stitching",
            ],
            "belt": ["cracked leather", "frayed edges", "worn holes", "peeling finish"],
            "watch": [
                "scratched face",
                "broken strap",
                "faded markings",
                "cracked casing",
            ],
            "glasses": [
                "scratched lenses",
                "bent frame",
                "loose arms",
                "cloudy lenses",
            ],
            "bicycle": ["flat tire", "rusty chain", "scratched frame", "worn seat"],
            "car tire": ["bald tread", "cracked rubber", "punctured", "worn sidewall"],
            "helmet": ["scratched shell", "cracked foam", "loose straps"],
            "tent": ["torn fabric", "bent poles", "moldy spots"],
            "grill": ["rusty grates", "blackened residue", "scratched body"],
            "garden hose": ["cracked", "leaking", "kinked", "faded"],
            "jeans": ["worn knees", "frayed hem", "ripped pocket", "faded"],
            "jacket": ["broken zipper", "faded color", "torn lining"],
            "gloves": ["frayed fingers", "stretched out", "stained"],
            "hat": ["faded color", "stretched", "frayed edges"],
            "scarf": ["pilled fabric", "snagged threads", "stained"],
            "socks": ["hole in toe", "stretched elastic", "faded"],
            "shoes": ["worn sole", "scuffed leather", "torn fabric", "faded color"],
            "phone": ["cracked screen", "scratched back", "worn buttons"],
            "laptop": ["scratched casing", "cracked hinge", "faded keyboard keys"],
            "TV remote": ["worn-out buttons", "cracked case", "faded labels"],
            "headphones": ["frayed cable", "scratched ear cups", "loose padding"],
            "key": ["bent", "worn teeth", "rusty", "scratched surface"],
            "battery": ["leaking", "corroded", "dented", "faded label"],
            "light bulb": ["burnt out", "cracked", "blackened", "loose filament"],
            "smooth wood plank Texture": [
                "cracked",
                "splintered",
                "warped",
                "knotted",
                "rotten",
                "scratched",
                "stained",
            ],
            "concrete Texture": [
                "cracked",
                "pitted",
                "stained",
                "eroded",
                "chipped",
                "weathered",
            ],
            "smooth glass Texture": [
                "scratched",
                "cracked",
                "chipped",
                "foggy",
                "stained",
                "shattered",
            ],
            "smooth metal Texture": [
                "rusted",
                "scratched",
                "dented",
                "corroded",
                "pitted",
                "tarnished",
            ],
            "fabric Texture": [
                "frayed",
                "torn",
                "stained",
                "faded",
                "pilled",
                "snagged",
            ],
            "paper Texture": [
                "torn",
                "wrinkled",
                "stained",
                "yellowed",
                "brittle",
                "moldy",
            ],
            "plastic Texture": [
                "scratched",
                "cracked",
                "discolored",
                "warped",
                "brittle",
                "faded",
            ],
            "smooth tile Texture": [
                "cracked",
                "chipped",
                "stained",
                "scratched",
                "dull",
                "loose",
            ],
            "carpet Texture": [
                "stained",
                "frayed",
                "worn",
                "faded",
                "pilled",
                "matted",
            ],
            "asphalt Texture": [
                "cracked",
                "pitted",
                "faded",
                "eroded",
                "oil-stained",
                "uneven",
            ],
            "stone tile Texture": [
                "chipped",
                "cracked",
                "eroded",
                "stained",
                "pitted",
                "weathered",
            ],
            "leather Texture": [
                "cracked",
                "faded",
                "scratched",
                "stained",
                "peeling",
                "dried out",
            ],
            "cork Texture": [
                "cracked",
                "crumbled",
                "stained",
                "dried out",
                "warped",
                "pitted",
            ],
            "rubber floor Texture": [
                "cracked",
                "brittle",
                "discolored",
                "stiffened",
                "melted",
                "torn",
            ],
            "velvet Texture": [
                "crushed",
                "faded",
                "stained",
                "pilled",
                "torn",
                "frayed",
            ],
            "linen Texture": [
                "wrinkled",
                "stained",
                "faded",
                "torn",
                "frayed",
                "pilled",
            ],
            "mesh Texture": [
                "frayed",
                "torn",
                "snagged",
                "discolored",
                "brittle",
                "stretched",
            ],
            "synthetic fiber Texture": [
                "frayed",
                "torn",
                "stained",
                "faded",
                "pilled",
                "melted",
            ],
            "fur Texture": ["matted", "shedding", "stained", "torn", "faded", "dull"],
            "denim Texture": ["frayed", "torn", "stained", "faded", "pilled", "worn"],
            "carbon fiber Texture": [
                "frayed",
                "chipped",
                "cracked",
                "delaminated",
                "scratched",
                "discolored",
            ],
            "wallpaper Texture": [
                "peeled",
                "torn",
                "stained",
                "faded",
                "bubbled",
                "wrinkled",
            ],
            "plywood Texture": [
                "warped",
                "splintered",
                "chipped",
                "stained",
                "delaminated",
                "cracked",
            ],
            "stainless steel Texture": [
                "scratched",
                "dented",
                "stained",
                "scuffed",
                "fingerprinted",
                "corroded",
            ],
            "brushed aluminum Texture": [
                "scratched",
                "dented",
                "stained",
                "faded",
                "oxidized",
                "pitted",
            ],
            "corrugated metal Texture": [
                "dented",
                "rusted",
                "bent",
                "scratched",
                "corroded",
                "pitted",
            ],
            "smooth ceramic tile Texture": [
                "chipped",
                "cracked",
                "stained",
                "crazed",
                "dull",
                "scratched",
            ],
            "mirror Texture": [
                "scratched",
                "cracked",
                "foggy",
                "stained",
                "warped",
                "discolored",
            ],
            "chalkboard Texture": [
                "scratched",
                "smudged",
                "cracked",
                "chipped",
                "stained",
                "uneven",
            ],
            "whiteboard Texture": [
                "scratched",
                "stained",
                "ghosting",
                "cracked",
                "faded",
                "dented",
            ],
            "laminate Texture": [
                "scratched",
                "chipped",
                "peeled",
                "bubbled",
                "stained",
                "warped",
            ],
            "hemp fabric Texture": [
                "frayed",
                "torn",
                "faded",
                "pilled",
                "stained",
                "snagged",
            ],
            "rattan Texture": [
                "splintered",
                "frayed",
                "cracked",
                "stained",
                "brittle",
                "discolored",
            ],
            "woven mat Texture": [
                "frayed",
                "torn",
                "faded",
                "loose fibers",
                "stained",
                "worn",
            ],
            "parquet flooring Texture": [
                "scratched",
                "warped",
                "faded",
                "chipped",
                "stained",
                "dull",
            ],
        }

        self.object_list = [
            "apple",
            "banana",
            "carrot",
            "potato",
            "egg",
            "bread",
            "cheese",
            "butter",
            "milk carton",
            "chocolate bar",
            "cookies",
            "apple slice",
            "orange",
            "grape",
            "strawberry",
            "lettuce",
            "tomato",
            "onion",
            "garlic",
            "hammer",
            "screwdriver",
            "wrench",
            "pliers",
            "saw",
            "drill",
            "tape measure",
            "paintbrush",
            "shovel",
            "rake",
            "ball",
            "doll",
            "teddy bear",
            "yo-yo",
            "kite",
            "toy car",
            "board game",
            "lamp",
            "chair",
            "table",
            "window",
            "mirror",
            "carpet",
            "toothbrush",
            "toothpaste tube",
            "wallet",
            "belt",
            "watch",
            "glasses",
            "bicycle",
            "car tire",
            "helmet",
            "tent",
            "grill",
            "garden hose",
            "jeans",
            "jacket",
            "gloves",
            "hat",
            "scarf",
            "socks",
            "shoes",
            "phone",
            "laptop",
            "TV remote",
            "headphones",
            "key",
            "battery",
            "light bulb",
            "smooth wood plank Texture",
            "concrete Texture",
            "smooth glass Texture",
            "smooth metal Texture",
            "fabric Texture",
            "paper Texture",
            "plastic Texture",
            "smooth tile Texture",
            "carpet Texture",
            "asphalt Texture",
            "stone tile Texture",
            "leather Texture",
            "cork Texture",
            "rubber floor Texture",
            "velvet Texture",
            "linen Texture",
            "mesh Texture",
            "synthetic fiber Texture",
            "fur Texture",
            "denim Texture",
            "carbon fiber Texture",
            "wallpaper Texture",
            "plywood Texture",
            "stainless steel Texture",
            "brushed aluminum Texture",
            "corrugated metal Texture",
            "smooth ceramic tile Texture",
            "mirror Texture",
            "chalkboard Texture",
            "whiteboard Texture",
            "laminate Texture",
            "hemp fabric Texture",
            "rattan Texture",
            "woven mat Texture",
            "parquet flooring Texture",
        ]
        self.backgrounds = [
            "wood",
            "marble",
            "concrete",
            "glass",
            "metal",
            "fabric",
            "paper",
            "plastic",
            "brick",
            "tile",
            "carpet",
            "grass",
            "sand",
            "gravel",
            "asphalt",
            "stone",
            "leather",
            "foam",
            "cork",
            "bamboo",
            "rubber",
            "velvet",
            "linen",
            "canvas",
            "mesh",
            "synthetic fiber",
            "fur",
            "denim",
            "carbon fiber",
            "granite",
            "pebbles",
            "water",
            "snow",
            "ice",
            "clouds",
            "wallpaper",
            "plywood",
            "wire mesh",
            "stainless steel",
            "brushed aluminum",
            "corrugated metal",
            "ceramic",
            "mirror",
            "painted wall",
            "chalkboard",
            "whiteboard",
            "laminate",
            "hemp fabric",
            "rattan",
            "woven mat",
            "terrazzo",
            "parquet flooring",
            "tarpaulin",
            "fleece",
        ]
